development:
  adapter: mysql
  encoding: utf8
  database: savage_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: savage_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: savage_production
  pool: 5
  username: root
  password:

